name: Synapse Non-Docker CI
on: [push]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Secret Scanner
        # This points to the local folder where your action lives
        uses: ./.github/actions/secret-scanner
        with:
          search_path: 'backend/config'